[[main]]
none = "none"

[[main]]
name = "Logs"
pre = "pencil"
pageRef = "logs"
identifier = "2M04yTpYht"
weight = 9_999

[[main]]
name = "About"
pre = "image"
pageRef = "about"
identifier = "Izb1M5UXxV"
weight = 9_999

[[main]]
name = "Projects"
pre = "list"
pageRef = "projects"
identifier = "VoQkv8oaqC"
weight = 9_999

[[footer]]
none = "none"
